apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dimitriosmikropoulos@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-menu
  template:
    metadata:
      labels:
        app: demo-menu
    spec:
      containers:
      - name: demo-menu
        image: ghcr.io/dmikropoulos/digitech-hosting/sites/demo-menu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-menu-svc
spec:
  selector:
    app: demo-menu
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-menu-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: 130.61.72.72.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-menu-svc
            port:
              number: 80
  tls:
  - hosts:
    - 130.61.72.72.nip.io
    secretName: demo-menu-tls